arena-mq:
  queueManager: MQLS01
  channel: Q1_FAMILIE_EF_IVERKS
  hostname: b27apvl219.preprod.local
  port: 1413
  queueName: QA.Q1_ARENA.VEDTAKHENDELSER_EF

DEPLOY_ENV: dev
ENSLIG_FORSORGER_VEDTAK_TOPIC: teamfamilie.aapen-ensligforsorger-vedtak-test
ENSLIG_FORSORGER_BEHANDLING_TOPIC: teamfamilie.aapen-ensligforsorger-behandling-test
prosessering.rolle: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS 928636f4-fd0d-4149-978e-a6fb68bb19de

TILBAKEKREVING_REQUEST_TOPIC:
